#!/bin/sh
# This file is to be sourced for versioning

VERSION_X=0 # Major
VERSION_Y=1 # Minor
VERSION_Z=0 # Patch

BRANDING_LONG="Vitality Linux"
BRANDING_SHORT="vitality"

VERSION_NUMBER="${VERSION_X}.${VERSION_Y}.${VERSION_Z}"
TIMESTAMP=$(date +\%Y.\%m.\%d)

VERSION_FULL="${BRANDING_LONG} v${VERSION_NUMBER} - Built on ${TIMESTAMP}"

BASE_DIR="/tmp/${BRANDING_SHORT}-v${VERSION_NUMBER}"
CHROOT_DIR="${BASE_DIR}/chroot"
RELEASE_DIR="${BASE_DIR}/release"
